import bcrypt from 'bcryptjs';
import { drizzle } from 'drizzle-orm/mysql2';

import { createConnection } from './index';
import * as schema from './schema';

async function main() {
  const connection = await createConnection();
  const db = drizzle(connection, { schema, mode: 'default' });

  // Use a fixed password hash for all users
  const hashedPassword = await bcrypt.hash('password123', 12);

  // Direct database inserts to ensure proper relationships
  await db.insert(schema.users).values([
    {
      id: 'user-1',
      email: 'staff@bizdocgen.com',
      password: hashedPassword,
      firstName: 'Asep',
      lastName: 'Staff',
      phone: '+6281234567890',
      role: 'staff',
      isActive: true,
    },
    {
      id: 'user-2',
      email: 'manager@bizdocgen.com',
      password: hashedPassword,
      firstName: 'Budi',
      lastName: 'Manager',
      phone: '+6281234567891',
      role: 'manager',
      isActive: true,
    },
    {
      id: 'user-3',
      email: 'director@bizdocgen.com',
      password: hashedPassword,
      firstName: 'Rizky',
      lastName: 'Director',
      phone: '+6281234567892',
      role: 'director',
      isActive: true,
    },
    {
      id: 'user-4',
      email: 'staff2@bizdocgen.com',
      password: hashedPassword,
      firstName: 'Rini',
      lastName: 'Susanti Staff',
      phone: '+6281234567893',
      role: 'staff',
      isActive: true,
    },
  ]);

  await db.insert(schema.customers).values([
    {
      id: 'customer-1',
      code: 'CUST001',
      name: 'PT Customer Pertama',
      email: 'contact@customerpertama.com',
      phone: '+6281234567897',
      address: 'Jl. Customer No. 1, Jakarta',
      city: 'Jakarta',
      country: 'Indonesia',
      taxNumber: '123456789012345',
      isActive: true,
    },
    {
      id: 'customer-2',
      code: 'CUST002',
      name: 'CV Customer Kedua',
      email: 'info@customerkedua.com',
      phone: '+6281234567898',
      address: 'Jl. Customer No. 2, Surabaya',
      city: 'Surabaya',
      country: 'Indonesia',
      taxNumber: '987654321098765',
      isActive: true,
    },
    {
      id: 'customer-3',
      code: 'CUST003',
      name: 'PT Customer Ketiga',
      email: 'contact@customerketiga.com',
      phone: '+6281234567899',
      address: 'Jl. Customer No. 3, Jakarta',
      city: 'Jakarta',
      country: 'Indonesia',
      taxNumber: '123456789012346',
      isActive: true,
    },
    {
      id: 'customer-4',
      code: 'CUST004',
      name: 'CV Customer Keempat',
      email: 'info@customerkeempat.com',
      phone: '+6281234567900',
      address: 'Jl. Customer No. 4, Surabaya',
      city: 'Surabaya',
      country: 'Indonesia',
      taxNumber: '987654321098766',
      isActive: true,
    },
    {
      id: 'customer-5',
      code: 'CUST005',
      name: 'PT Customer Kelima',
      email: 'contact@customerkelima.com',
      phone: '+6281234567901',
      address: 'Jl. Customer No. 5, Jakarta',
      city: 'Jakarta',
      country: 'Indonesia',
      taxNumber: '123456789012347',
      isActive: true,
    },
  ]);

  await db.insert(schema.suppliers).values([
    {
      id: 'supplier-1',
      code: 'SUP001',
      name: 'PT Supplier Utama',
      contactPerson: 'John Doe',
      email: 'contact@supplierutama.com',
      phone: '+6281234567893',
      address: 'Jl. Supplier No. 123',
      city: 'Jakarta',
      country: 'Indonesia',
      taxNumber: '123456789012345',
      isActive: true,
    },
    {
      id: 'supplier-2',
      code: 'SUP002',
      name: 'CV Supplier Mitra',
      contactPerson: 'Jane Smith',
      email: 'info@suppliermitra.com',
      phone: '+6281234567894',
      address: 'Jl. Mitra No. 456',
      city: 'Surabaya',
      country: 'Indonesia',
      taxNumber: '987654321098765',
      isActive: true,
    },
    {
      id: 'supplier-3',
      code: 'SUP003',
      name: 'PT Supplier Ketiga',
      contactPerson: 'Ahmad Rizki',
      email: 'contact@supplierketiga.com',
      phone: '+6281234567895',
      address: 'Jl. Supplier No. 789',
      city: 'Bekasi',
      country: 'Indonesia',
      taxNumber: '123456789012348',
      isActive: true,
    },
  ]);

  await db.insert(schema.warehouses).values([
    {
      id: 'warehouse-1',
      code: 'WH001',
      name: 'Warehouse Jakarta Pusat',
      address: 'Jl. Warehouse No. 1',
      city: 'Jakarta',
      country: 'Indonesia',
      manager: 'Warehouse Manager Jakarta',
      phone: '+6281234567895',
      isActive: true,
    },
    {
      id: 'warehouse-2',
      code: 'WH002',
      name: 'Warehouse Surabaya',
      address: 'Jl. Warehouse No. 2',
      city: 'Surabaya',
      country: 'Indonesia',
      manager: 'Warehouse Manager Surabaya',
      phone: '+6281234567896',
      isActive: true,
    },
  ]);

  await db.insert(schema.products).values([
    {
      id: 'product-1',
      code: 'SHA-1750609617450-853',
      name: 'Shantui L36-B3',
      description: 'Wheel Loader for construction and material handling',
      category: 'wheel_loader',
      brand: 'Shantui',
      model: 'L36-B3',
      year: 2025,
      condition: 'new',
      status: 'in_stock',
      location: 'Jakarta Warehouse',
      unit: 'pcs',
      price: '185000000.00',
      currency: 'IDR',
      supplierId: 'supplier-1',
      isActive: true,
    },
    {
      id: 'product-2',
      code: 'SHA-1749810376237-569',
      name: 'Shantui L36-B3',
      description: 'Wheel Loader for construction and material handling',
      category: 'wheel_loader',
      brand: 'Shantui',
      model: 'L36-B3',
      year: 2023,
      condition: 'used',
      status: 'reserved',
      location: 'Jakarta Warehouse',
      unit: 'pcs',
      price: '145000000.00',
      currency: 'IDR',
      supplierId: 'supplier-1',
      isActive: true,
    },
    {
      id: 'product-3',
      code: 'SHA-1749809344351-476',
      name: 'Shantui SL36-B3',
      description: 'Wheel Loader for construction and material handling',
      category: 'wheel_loader',
      brand: 'Shantui',
      model: 'SL36-B3',
      year: 2019,
      condition: 'used',
      status: 'in_stock',
      location: 'Jakarta Warehouse',
      unit: 'pcs',
      price: '95000000.00',
      currency: 'IDR',
      supplierId: 'supplier-1',
      isActive: true,
    },
    {
      id: 'product-4',
      code: 'SHA-1749715519206-385',
      name: 'Shantui DH08-B3-XL',
      description: 'Bulldozer for earthmoving and construction',
      category: 'bulldozer',
      brand: 'Shantui',
      model: 'DH08-B3-XL',
      year: 2024,
      condition: 'new',
      status: 'in_stock',
      location: 'Jakarta Warehouse',
      unit: 'pcs',
      price: '220000000.00',
      currency: 'IDR',
      supplierId: 'supplier-1',
      isActive: true,
    },
    {
      id: 'product-5',
      code: 'SHA-1749713879644-288',
      name: 'Shantui SFD35 - 3000',
      description: 'Excavator for construction and digging operations',
      category: 'excavator',
      brand: 'Shantui',
      model: 'SFD35 - 3000',
      year: 2022,
      condition: 'used',
      status: 'maintenance',
      location: 'Jakarta Warehouse',
      unit: 'pcs',
      price: '165000000.00',
      currency: 'IDR',
      supplierId: 'supplier-1',
      isActive: true,
    },
    {
      id: 'product-6',
      code: 'SHA-1749615913191-381',
      name: 'Shantui SR 20H-B6',
      description: 'Compactor for road construction and maintenance',
      category: 'compactor',
      brand: 'Shantui',
      model: 'SR 20H-B6',
      year: 2025,
      condition: 'new',
      status: 'in_stock',
      location: 'Surabaya Warehouse',
      unit: 'pcs',
      price: '135000000.00',
      currency: 'IDR',
      supplierId: 'supplier-1',
      isActive: true,
    },
    {
      id: 'product-7',
      code: 'SHA-1749615117434-413',
      name: 'Shantui SFD70-3000',
      description: 'Forklift for material handling and warehouse operations',
      category: 'forklift',
      brand: 'Shantui',
      model: 'SFD70-3000',
      year: 2021,
      condition: 'used',
      status: 'in_stock',
      location: 'Surabaya Warehouse',
      unit: 'pcs',
      price: '85000000.00',
      currency: 'IDR',
      supplierId: 'supplier-1',
      isActive: true,
    },
    {
      id: 'product-8',
      code: 'SHA-1749532223148-878',
      name: 'Shantui SD16F',
      description: 'Bulldozer for earthmoving and construction',
      category: 'bulldozer',
      brand: 'Shantui',
      model: 'SD16F',
      year: 2025,
      condition: 'new',
      status: 'reserved',
      location: 'Jakarta Warehouse',
      unit: 'pcs',
      price: '195000000.00',
      currency: 'IDR',
      supplierId: 'supplier-1',
      isActive: true,
    },
    {
      id: 'product-9',
      code: 'SHA-1749462416657-376',
      name: 'Shantui SD17',
      description: 'Bulldozer for earthmoving and construction',
      category: 'bulldozer',
      brand: 'Shantui',
      model: 'SD17',
      year: 2020,
      condition: 'used',
      status: 'in_stock',
      location: 'Jakarta Warehouse',
      unit: 'pcs',
      price: '125000000.00',
      currency: 'IDR',
      supplierId: 'supplier-1',
      isActive: true,
    },
    {
      id: 'product-10',
      code: 'SHA-1749458225471-648',
      name: 'Shantui SE75',
      description: 'Excavator for construction and digging operations',
      category: 'excavator',
      brand: 'Shantui',
      model: 'SE75',
      year: 2025,
      condition: 'new',
      status: 'in_stock',
      location: 'Surabaya Warehouse',
      unit: 'pcs',
      price: '175000000.00',
      currency: 'IDR',
      supplierId: 'supplier-1',
      isActive: true,
    },
    {
      id: 'product-11',
      code: 'CAT-1749458225471-649',
      name: 'Caterpillar 320',
      description: 'Hydraulic excavator for heavy construction and mining',
      category: 'excavator',
      brand: 'Caterpillar',
      model: '320',
      year: 2024,
      condition: 'new',
      status: 'in_stock',
      location: 'Jakarta Warehouse',
      unit: 'pcs',
      price: '420000000.00',
      currency: 'IDR',
      supplierId: 'supplier-2',
      isActive: true,
    },
    {
      id: 'product-12',
      code: 'KOM-1749458225471-650',
      name: 'Komatsu PC200-8',
      description: 'Hydraulic excavator for construction and earthmoving',
      category: 'excavator',
      brand: 'Komatsu',
      model: 'PC200-8',
      year: 2023,
      condition: 'used',
      status: 'maintenance',
      location: 'Jakarta Warehouse',
      unit: 'pcs',
      price: '280000000.00',
      currency: 'IDR',
      supplierId: 'supplier-3',
      isActive: true,
    },
    {
      id: 'product-13',
      code: 'HIT-1749458225471-651',
      name: 'Hitachi ZX200-5G',
      description: 'Hydraulic excavator with advanced fuel efficiency',
      category: 'excavator',
      brand: 'Hitachi',
      model: 'ZX200-5G',
      year: 2025,
      condition: 'new',
      status: 'in_stock',
      location: 'Surabaya Warehouse',
      unit: 'pcs',
      price: '380000000.00',
      currency: 'IDR',
      supplierId: 'supplier-2',
      isActive: true,
    },
    {
      id: 'product-14',
      code: 'VOL-1749458225471-652',
      name: 'Volvo EC200D',
      description: 'Crawler excavator for construction and material handling',
      category: 'excavator',
      brand: 'Volvo',
      model: 'EC200D',
      year: 2022,
      condition: 'used',
      status: 'in_stock',
      location: 'Jakarta Warehouse',
      unit: 'pcs',
      price: '320000000.00',
      currency: 'IDR',
      supplierId: 'supplier-1',
      isActive: true,
    },
    {
      id: 'product-15',
      code: 'JCB-1749458225471-653',
      name: 'JCB 3DX',
      description: 'Backhoe loader for versatile construction applications',
      category: 'backhoe_loader',
      brand: 'JCB',
      model: '3DX',
      year: 2025,
      condition: 'new',
      status: 'reserved',
      location: 'Surabaya Warehouse',
      unit: 'pcs',
      price: '320000000.00',
      currency: 'IDR',
      supplierId: 'supplier-3',
      isActive: true,
    },
    {
      id: 'product-16',
      code: 'CAT-1749458225471-654',
      name: 'Caterpillar 950K',
      description: 'Wheel loader for heavy-duty material handling',
      category: 'wheel_loader',
      brand: 'Caterpillar',
      model: '950K',
      year: 2024,
      condition: 'new',
      status: 'in_stock',
      location: 'Jakarta Warehouse',
      unit: 'pcs',
      price: '450000000.00',
      currency: 'IDR',
      supplierId: 'supplier-2',
      isActive: true,
    },
    {
      id: 'product-17',
      code: 'KOM-1749458225471-655',
      name: 'Komatsu D65PX-18',
      description: 'Bulldozer for earthmoving and construction',
      category: 'bulldozer',
      brand: 'Komatsu',
      model: 'D65PX-18',
      year: 2021,
      condition: 'used',
      status: 'in_stock',
      location: 'Surabaya Warehouse',
      unit: 'pcs',
      price: '280000000.00',
      currency: 'IDR',
      supplierId: 'supplier-3',
      isActive: true,
    },
    {
      id: 'product-18',
      code: 'HIT-1749458225471-656',
      name: 'Hitachi ZW310-6',
      description: 'Wheel loader for construction and material handling',
      category: 'wheel_loader',
      brand: 'Hitachi',
      model: 'ZW310-6',
      year: 2023,
      condition: 'used',
      status: 'maintenance',
      location: 'Jakarta Warehouse',
      unit: 'pcs',
      price: '220000000.00',
      currency: 'IDR',
      supplierId: 'supplier-2',
      isActive: true,
    },
    {
      id: 'product-19',
      code: 'VOL-1749458225471-657',
      name: 'Volvo L90H',
      description: 'Wheel loader for heavy construction applications',
      category: 'wheel_loader',
      brand: 'Volvo',
      model: 'L90H',
      year: 2025,
      condition: 'new',
      status: 'in_stock',
      location: 'Surabaya Warehouse',
      unit: 'pcs',
      price: '380000000.00',
      currency: 'IDR',
      supplierId: 'supplier-1',
      isActive: true,
    },
    {
      id: 'product-20',
      code: 'CAT-1749458225471-658',
      name: 'Caterpillar D6T',
      description: 'Bulldozer for earthmoving and construction',
      category: 'bulldozer',
      brand: 'Caterpillar',
      model: 'D6T',
      year: 2020,
      condition: 'used',
      status: 'in_stock',
      location: 'Jakarta Warehouse',
      unit: 'pcs',
      price: '350000000.00',
      currency: 'IDR',
      supplierId: 'supplier-2',
      isActive: true,
    },
  ]);

  await db.insert(schema.quotations).values([
    {
      id: 'quotation-1',
      quotationNumber: 'QT/2025/04/001',
      quotationDate: new Date('2025-04-29'),
      validUntil: new Date('2025-07-29'),
      customerId: 'customer-1',
      createdBy: 'user-1',
      isIncludePPN: true,
      subtotal: '15000000.00',
      tax: '1500000.00',
      total: '16500000.00',
      currency: 'IDR',
      status: 'draft',
      notes: 'Standard quotation for heavy equipment',
      termsAndConditions: null,
    },
    {
      id: 'quotation-2',
      quotationNumber: 'QT/2025/04/002',
      quotationDate: new Date('2025-04-29'),
      validUntil: new Date('2025-07-29'),
      customerId: 'customer-2',
      createdBy: 'user-2',
      isIncludePPN: false,
      subtotal: '25000000.00',
      tax: '0.00',
      total: '25000000.00',
      currency: 'IDR',
      status: 'sent',
      notes: 'Special pricing for bulk order',
      termsAndConditions: null,
    },
    {
      id: 'quotation-3',
      quotationNumber: 'QT/2025/05/001',
      quotationDate: new Date('2025-05-29'),
      validUntil: new Date('2025-07-29'),
      customerId: 'customer-3',
      createdBy: 'user-1',
      isIncludePPN: true,
      subtotal: '35000000.00',
      tax: '3500000.00',
      total: '38500000.00',
      currency: 'IDR',
      status: 'accepted',
      notes: 'Premium equipment package',
      termsAndConditions: null,
    },
    {
      id: 'quotation-4',
      quotationNumber: 'QT/2025/06/001',
      quotationDate: new Date('2025-01-30'),
      validUntil: new Date('2025-02-30'),
      customerId: 'customer-4',
      createdBy: 'user-3',
      isIncludePPN: true,
      subtotal: '18000000.00',
      tax: '1800000.00',
      total: '19800000.00',
      currency: 'IDR',
      status: 'rejected',
      notes: 'Budget constraints',
      termsAndConditions: null,
    },
    {
      id: 'quotation-5',
      quotationNumber: 'QT/2025/06/002',
      quotationDate: new Date('2025-06-15'),
      validUntil: new Date('2025-07-15'),
      customerId: 'customer-5',
      createdBy: 'user-4',
      isIncludePPN: true,
      subtotal: '42000000.00',
      tax: '4200000.00',
      total: '46200000.00',
      currency: 'IDR',
      status: 'draft',
      notes: 'Caterpillar excavator for mining operations',
      termsAndConditions: null,
    },
    {
      id: 'quotation-6',
      quotationNumber: 'QT/2025/06/003',
      quotationDate: new Date('2025-06-20'),
      validUntil: new Date('2025-07-20'),
      customerId: 'customer-1',
      createdBy: 'user-2',
      isIncludePPN: false,
      subtotal: '28000000.00',
      tax: '0.00',
      total: '28000000.00',
      currency: 'IDR',
      status: 'sent',
      notes: 'Komatsu excavator for infrastructure project',
      termsAndConditions: null,
    },
    {
      id: 'quotation-7',
      quotationNumber: 'QT/2025/09/001',
      quotationDate: new Date('2025-09-10'),
      validUntil: new Date('2025-12-10'),
      customerId: 'customer-2',
      createdBy: 'user-1',
      isIncludePPN: true,
      subtotal: '32000000.00',
      tax: '3200000.00',
      total: '35200000.00',
      currency: 'IDR',
      status: 'accepted',
      notes: 'JCB backhoe loader for construction site',
      termsAndConditions: null,
    },
  ]);

  await db.insert(schema.quotationItems).values([
    {
      id: 'item-1',
      quotationId: 'quotation-1',
      productId: 'product-1',
      quantity: '1.00',
      unitPrice: '15000000.00',
      total: '15000000.00',
      notes: 'Wheel loader with standard configuration',
    },
    {
      id: 'item-2',
      quotationId: 'quotation-2',
      productId: 'product-2',
      quantity: '1.00',
      unitPrice: '25000000.00',
      total: '25000000.00',
      notes: 'Wheel loader with premium features',
    },
    {
      id: 'item-3',
      quotationId: 'quotation-3',
      productId: 'product-4',
      quantity: '1.00',
      unitPrice: '35000000.00',
      total: '35000000.00',
      notes: 'Bulldozer with advanced controls',
    },
    {
      id: 'item-4',
      quotationId: 'quotation-4',
      productId: 'product-5',
      quantity: '1.00',
      unitPrice: '18000000.00',
      total: '18000000.00',
      notes: 'Excavator for construction project',
    },
    {
      id: 'item-5',
      quotationId: 'quotation-5',
      productId: 'product-11',
      quantity: '1.00',
      unitPrice: '42000000.00',
      total: '42000000.00',
      notes: 'Caterpillar excavator for mining operations',
    },
    {
      id: 'item-6',
      quotationId: 'quotation-6',
      productId: 'product-12',
      quantity: '1.00',
      unitPrice: '28000000.00',
      total: '28000000.00',
      notes: 'Komatsu excavator for infrastructure project',
    },
    {
      id: 'item-7',
      quotationId: 'quotation-7',
      productId: 'product-15',
      quantity: '1.00',
      unitPrice: '32000000.00',
      total: '32000000.00',
      notes: 'JCB backhoe loader for construction site',
    },
  ]);

  await connection.end();
  console.log('✅ Database seeded successfully!');
}

main().catch((error) => {
  console.error('❌ Error seeding database:', error);
  process.exit(1);
});
