import { randomUUID } from 'crypto';
import bcrypt from 'bcryptjs';
import { drizzle } from 'drizzle-orm/mysql2';

import { createConnection } from './index';
import * as schema from './schema';

async function main() {
  const connection = await createConnection();
  const db = drizzle(connection, { schema, mode: 'default' });

  // Use a fixed password hash for all users
  const hashedPassword = await bcrypt.hash('password123', 12);

  // Generate UUIDs for consistent reference
  const userIds = {
    user1: randomUUID(),
    user2: randomUUID(),
    user3: randomUUID(),
    user4: randomUUID(),
  };

  const customerIds = {
    customer1: randomUUID(),
    customer2: randomUUID(),
    customer3: randomUUID(),
    customer4: randomUUID(),
    customer5: randomUUID(),
  };

  const supplierIds = {
    supplier1: randomUUID(),
    supplier2: randomUUID(),
    supplier3: randomUUID(),
  };

  const warehouseIds = {
    warehouse1: randomUUID(),
    warehouse2: randomUUID(),
  };

  const productIds = {
    product1: randomUUID(),
    product2: randomUUID(),
    product3: randomUUID(),
    product4: randomUUID(),
    product5: randomUUID(),
    product6: randomUUID(),
    product7: randomUUID(),
    product8: randomUUID(),
    product9: randomUUID(),
    product10: randomUUID(),
    product11: randomUUID(),
    product12: randomUUID(),
    product13: randomUUID(),
    product14: randomUUID(),
    product15: randomUUID(),
    product16: randomUUID(),
    product17: randomUUID(),
    product18: randomUUID(),
    product19: randomUUID(),
    product20: randomUUID(),
  };

  const quotationIds = {
    quotation1: randomUUID(),
    quotation2: randomUUID(),
    quotation3: randomUUID(),
    quotation4: randomUUID(),
    quotation5: randomUUID(),
    quotation6: randomUUID(),
    quotation7: randomUUID(),
    quotation8: randomUUID(),
    quotation9: randomUUID(),
  };

  const invoiceIds = {
    invoice1: randomUUID(),
    invoice2: randomUUID(),
    invoice3: randomUUID(),
    invoice4: randomUUID(),
    invoice5: randomUUID(),
    invoice6: randomUUID(),
  };

  const deliveryNoteIds = {
    deliveryNote1: randomUUID(),
    deliveryNote2: randomUUID(),
    deliveryNote3: randomUUID(),
    deliveryNote4: randomUUID(),
  };

  // Direct database inserts to ensure proper relationships
  console.log('🔄 Seeding users...');
  await db.insert(schema.users).values([
    {
      id: userIds.user1,
      code: 'USR001',
      firstName: 'Asep',
      lastName: 'Staff',
      NIK: '1234567890123456',
      email: 'staff@bizdocgen.com',
      password: hashedPassword,
      jobTitle: 'Sales Staff',
      joinDate: new Date('2024-01-15'),
      type: 'full-time',
      phone: '+6281234567890',
      avatar: null,
      role: 'staff',
      signature: null,
      isActive: true,
    },
    {
      id: userIds.user2,
      code: 'USR002',
      firstName: 'Budi',
      lastName: 'Manager',
      NIK: '1234567890123457',
      email: 'manager@bizdocgen.com',
      password: hashedPassword,
      jobTitle: 'Sales Manager',
      joinDate: new Date('2023-06-01'),
      type: 'full-time',
      phone: '+6281234567891',
      avatar: null,
      role: 'manager',
      signature: null,
      isActive: true,
    },
    {
      id: userIds.user3,
      code: 'USR003',
      firstName: 'Rizky',
      lastName: 'Director',
      NIK: '1234567890123458',
      email: 'director@bizdocgen.com',
      password: hashedPassword,
      jobTitle: 'Director',
      joinDate: new Date('2022-01-01'),
      type: 'full-time',
      phone: '+6281234567892',
      avatar: null,
      role: 'director',
      signature: null,
      isActive: true,
    },
    {
      id: userIds.user4,
      code: 'USR004',
      firstName: 'Rini',
      lastName: 'Susanti Staff',
      NIK: '1234567890123459',
      email: 'staff2@bizdocgen.com',
      password: hashedPassword,
      jobTitle: 'Sales Staff',
      joinDate: new Date('2024-03-01'),
      type: 'full-time',
      phone: '+6281234567893',
      avatar: null,
      role: 'staff',
      signature: null,
      isActive: true,
    },
  ]);
  console.log('✅ Seeded 4 users');

  console.log('🔄 Seeding customers...');
  await db.insert(schema.customers).values([
    {
      id: customerIds.customer1,
      code: 'CUST001',
      name: 'PT Customer Pertama',
      type: 'company',
      npwp: '12.345.678.9-123.456',
      npwp16: '12.345.678.9-123.456',
      billingAddress: 'Jl. Customer No. 1, Jakarta Pusat, DKI Jakarta 10110',
      shippingAddress: 'Jl. Customer No. 1, Jakarta Pusat, DKI Jakarta 10110',
      contactPersonName: 'John Doe',
      contactPersonEmail: 'contact@customerpertama.com',
      contactPersonPhone: '+6281234567897',
      paymentTerms: 'NET 30',
      isPPN: true,
    },
    {
      id: customerIds.customer2,
      code: 'CUST002',
      name: 'CV Customer Kedua',
      type: 'company',
      npwp: '12.345.678.9-123.457',
      npwp16: '12.345.678.9-123.457',
      billingAddress: 'Jl. Customer No. 2, Surabaya, Jawa Timur 60111',
      shippingAddress: 'Jl. Customer No. 2, Surabaya, Jawa Timur 60111',
      contactPersonName: 'Jane Smith',
      contactPersonEmail: 'info@customerkedua.com',
      contactPersonPhone: '+6281234567898',
      paymentTerms: 'NET 15',
      isPPN: false,
    },
    {
      id: customerIds.customer3,
      code: 'CUST003',
      name: 'PT Customer Ketiga',
      type: 'company',
      npwp: '12.345.678.9-123.458',
      npwp16: '12.345.678.9-123.458',
      billingAddress: 'Jl. Customer No. 3, Jakarta Selatan, DKI Jakarta 12120',
      shippingAddress: 'Jl. Customer No. 3, Jakarta Selatan, DKI Jakarta 12120',
      contactPersonName: 'Ahmad Rizki',
      contactPersonEmail: 'contact@customerketiga.com',
      contactPersonPhone: '+6281234567899',
      paymentTerms: 'NET 30',
      isPPN: true,
    },
    {
      id: customerIds.customer4,
      code: 'CUST004',
      name: 'CV Customer Keempat',
      type: 'company',
      npwp: '12.345.678.9-123.459',
      npwp16: '12.345.678.9-123.459',
      billingAddress: 'Jl. Customer No. 4, Surabaya, Jawa Timur 60112',
      shippingAddress: 'Jl. Customer No. 4, Surabaya, Jawa Timur 60112',
      contactPersonName: 'Siti Nurhaliza',
      contactPersonEmail: 'info@customerkeempat.com',
      contactPersonPhone: '+6281234567900',
      paymentTerms: 'NET 15',
      isPPN: false,
    },
    {
      id: customerIds.customer5,
      code: 'CUST005',
      name: 'PT Customer Kelima',
      type: 'company',
      npwp: '12.345.678.9-123.460',
      npwp16: '12.345.678.9-123.460',
      billingAddress: 'Jl. Customer No. 5, Jakarta Barat, DKI Jakarta 11420',
      shippingAddress: 'Jl. Customer No. 5, Jakarta Barat, DKI Jakarta 11420',
      contactPersonName: 'Budi Santoso',
      contactPersonEmail: 'contact@customerkelima.com',
      contactPersonPhone: '+6281234567901',
      paymentTerms: 'NET 30',
      isPPN: true,
    },
  ]);
  console.log('✅ Seeded 5 customers');

  console.log('🔄 Seeding suppliers...');
  await db.insert(schema.suppliers).values([
    {
      id: supplierIds.supplier1,
      code: 'SUP001',
      name: 'PT Supplier Utama',
      country: 'Indonesia',
      address: 'Jl. Supplier No. 123, Jakarta Pusat, DKI Jakarta 10110',
      transactionCurrency: 'IDR',
      postalCode: '10110',
      contactPersonName: 'John Doe',
      contactPersonEmail: 'contact@supplierutama.com',
      contactPersonPhone: '+6281234567893',
      isActive: true,
    },
    {
      id: supplierIds.supplier2,
      code: 'SUP002',
      name: 'CV Supplier Mitra',
      country: 'Indonesia',
      address: 'Jl. Mitra No. 456, Surabaya, Jawa Timur 60111',
      transactionCurrency: 'IDR',
      postalCode: '60111',
      contactPersonName: 'Jane Smith',
      contactPersonEmail: 'info@suppliermitra.com',
      contactPersonPhone: '+6281234567894',
      isActive: true,
    },
    {
      id: supplierIds.supplier3,
      code: 'SUP003',
      name: 'PT Supplier Ketiga',
      country: 'Indonesia',
      address: 'Jl. Supplier No. 789, Bekasi, Jawa Barat 17111',
      transactionCurrency: 'IDR',
      postalCode: '17111',
      contactPersonName: 'Ahmad Rizki',
      contactPersonEmail: 'contact@supplierketiga.com',
      contactPersonPhone: '+6281234567895',
      isActive: true,
    },
  ]);
  console.log('✅ Seeded 3 suppliers');

  console.log('🔄 Seeding warehouses...');
  await db.insert(schema.warehouses).values([
    {
      id: warehouseIds.warehouse1,
      code: 'WH001',
      name: 'Warehouse Jakarta Pusat',
      address: 'Jl. Warehouse No. 1',
      city: 'Jakarta',
      country: 'Indonesia',
      manager: 'Warehouse Manager Jakarta',
      phone: '+6281234567895',
      isActive: true,
    },
    {
      id: warehouseIds.warehouse2,
      code: 'WH002',
      name: 'Warehouse Surabaya',
      address: 'Jl. Warehouse No. 2',
      city: 'Surabaya',
      country: 'Indonesia',
      manager: 'Warehouse Manager Surabaya',
      phone: '+6281234567896',
      isActive: true,
    },
  ]);
  console.log('✅ Seeded 2 warehouses');

  console.log('🔄 Seeding products...');
  await db.insert(schema.products).values([
    {
      id: productIds.product1,
      code: 'SHA-1750609617450-853',
      name: 'Shantui L36-B3',
      description: 'Wheel Loader for construction and material handling',
      category: 'wheel_loader',
      brand: 'Shantui',
      model: 'L36-B3',
      year: 2025,
      condition: 'new',
      status: 'in_stock',
      location: 'Jakarta Warehouse',
      unit: 'pcs',
      price: '185000000.00',
      currency: 'IDR',
      engineModel: 'WD10G220E23',
      enginePower: '220 hp',
      operatingWeight: '18,500 kg',
      supplierId: supplierIds.supplier1,
      isActive: true,
    },
    {
      id: productIds.product2,
      code: 'SHA-1749810376237-569',
      name: 'Shantui L36-B3',
      description: 'Wheel Loader for construction and material handling',
      category: 'wheel_loader',
      brand: 'Shantui',
      model: 'L36-B3',
      year: 2023,
      condition: 'used',
      status: 'reserved',
      location: 'Jakarta Warehouse',
      unit: 'pcs',
      price: '145000000.00',
      currency: 'IDR',
      engineModel: 'WD10G220E23',
      enginePower: '220 hp',
      operatingWeight: '18,500 kg',
      supplierId: supplierIds.supplier1,
      isActive: true,
    },
    {
      id: productIds.product3,
      code: 'SHA-1749809344351-476',
      name: 'Shantui SL36-B3',
      description: 'Wheel Loader for construction and material handling',
      category: 'wheel_loader',
      brand: 'Shantui',
      model: 'SL36-B3',
      year: 2019,
      condition: 'used',
      status: 'in_stock',
      location: 'Jakarta Warehouse',
      unit: 'pcs',
      price: '95000000.00',
      currency: 'IDR',
      engineModel: 'WD10G220E23',
      enginePower: '220 hp',
      operatingWeight: '18,500 kg',
      supplierId: supplierIds.supplier1,
      isActive: true,
    },
    {
      id: productIds.product4,
      code: 'SHA-1749715519206-385',
      name: 'Shantui DH08-B3-XL',
      description: 'Bulldozer for earthmoving and construction',
      category: 'bulldozer',
      brand: 'Shantui',
      model: 'DH08-B3-XL',
      year: 2024,
      condition: 'new',
      status: 'in_stock',
      location: 'Jakarta Warehouse',
      unit: 'pcs',
      price: '220000000.00',
      currency: 'IDR',
      engineModel: 'Cummins NT855-C360',
      enginePower: '360 hp',
      operatingWeight: '32,000 kg',
      supplierId: supplierIds.supplier1,
      isActive: true,
    },
    {
      id: productIds.product5,
      code: 'SHA-1749713879644-288',
      name: 'Shantui SFD35 - 3000',
      description: 'Excavator for construction and digging operations',
      category: 'excavator',
      brand: 'Shantui',
      model: 'SFD35 - 3000',
      year: 2022,
      condition: 'used',
      status: 'maintenance',
      location: 'Jakarta Warehouse',
      unit: 'pcs',
      price: '165000000.00',
      currency: 'IDR',
      engineModel: 'Cummins NT855-C360',
      enginePower: '360 hp',
      operatingWeight: '35,000 kg',
      supplierId: supplierIds.supplier1,
      isActive: true,
    },
    {
      id: productIds.product6,
      code: 'SHA-1749615913191-381',
      name: 'Shantui SR 20H-B6',
      description: 'Compactor for road construction and maintenance',
      category: 'compactor',
      brand: 'Shantui',
      model: 'SR 20H-B6',
      year: 2025,
      condition: 'new',
      status: 'in_stock',
      location: 'Surabaya Warehouse',
      unit: 'pcs',
      price: '135000000.00',
      currency: 'IDR',
      engineModel: 'Cummins NT855-C360',
      enginePower: '360 hp',
      operatingWeight: '20,000 kg',
      supplierId: supplierIds.supplier1,
      isActive: true,
    },
    {
      id: productIds.product7,
      code: 'SHA-1749615117434-413',
      name: 'Shantui SFD70-3000',
      description: 'Forklift for material handling and warehouse operations',
      category: 'forklift',
      brand: 'Shantui',
      model: 'SFD70-3000',
      year: 2021,
      condition: 'used',
      status: 'in_stock',
      location: 'Surabaya Warehouse',
      unit: 'pcs',
      price: '85000000.00',
      currency: 'IDR',
      engineModel: 'Cummins B3.3-C85',
      enginePower: '85 hp',
      operatingWeight: '7,000 kg',
      supplierId: supplierIds.supplier1,
      isActive: true,
    },
    {
      id: productIds.product8,
      code: 'SHA-1749532223148-878',
      name: 'Shantui SD16F',
      description: 'Bulldozer for earthmoving and construction',
      category: 'bulldozer',
      brand: 'Shantui',
      model: 'SD16F',
      year: 2025,
      condition: 'new',
      status: 'reserved',
      location: 'Jakarta Warehouse',
      unit: 'pcs',
      price: '195000000.00',
      currency: 'IDR',
      engineModel: 'Cummins NT855-C360',
      enginePower: '360 hp',
      operatingWeight: '16,000 kg',
      supplierId: supplierIds.supplier1,
      isActive: true,
    },
    {
      id: productIds.product9,
      code: 'SHA-1749462416657-376',
      name: 'Shantui SD17',
      description: 'Bulldozer for earthmoving and construction',
      category: 'bulldozer',
      brand: 'Shantui',
      model: 'SD17',
      year: 2020,
      condition: 'used',
      status: 'in_stock',
      location: 'Jakarta Warehouse',
      unit: 'pcs',
      price: '125000000.00',
      currency: 'IDR',
      engineModel: 'Cummins NT855-C360',
      enginePower: '360 hp',
      operatingWeight: '17,000 kg',
      supplierId: supplierIds.supplier1,
      isActive: true,
    },
    {
      id: productIds.product10,
      code: 'SHA-1749458225471-648',
      name: 'Shantui SE75',
      description: 'Excavator for construction and digging operations',
      category: 'excavator',
      brand: 'Shantui',
      model: 'SE75',
      year: 2025,
      condition: 'new',
      status: 'in_stock',
      location: 'Surabaya Warehouse',
      unit: 'pcs',
      price: '175000000.00',
      currency: 'IDR',
      engineModel: 'Cummins NT855-C360',
      enginePower: '360 hp',
      operatingWeight: '7,500 kg',
      supplierId: supplierIds.supplier1,
      isActive: true,
    },
    {
      id: productIds.product11,
      code: 'CAT-1749458225471-649',
      name: 'Caterpillar 320',
      description: 'Hydraulic excavator for heavy construction and mining',
      category: 'excavator',
      brand: 'Caterpillar',
      model: '320',
      year: 2024,
      condition: 'new',
      status: 'in_stock',
      location: 'Jakarta Warehouse',
      unit: 'pcs',
      price: '420000000.00',
      currency: 'IDR',
      engineModel: 'Cat C7.1',
      enginePower: '103 kW (138 hp)',
      operatingWeight: '20,000 kg',
      supplierId: supplierIds.supplier2,
      isActive: true,
    },
    {
      id: productIds.product12,
      code: 'KOM-1749458225471-650',
      name: 'Komatsu PC200-8',
      description: 'Hydraulic excavator for construction and earthmoving',
      category: 'excavator',
      brand: 'Komatsu',
      model: 'PC200-8',
      year: 2023,
      condition: 'used',
      status: 'maintenance',
      location: 'Jakarta Warehouse',
      unit: 'pcs',
      price: '280000000.00',
      currency: 'IDR',
      engineModel: 'SAA6D107E-1',
      enginePower: '110 kW (148 hp)',
      operatingWeight: '20,500 kg',
      supplierId: supplierIds.supplier3,
      isActive: true,
    },
    {
      id: productIds.product13,
      code: 'HIT-1749458225471-651',
      name: 'Hitachi ZX200-5G',
      description: 'Hydraulic excavator with advanced fuel efficiency',
      category: 'excavator',
      brand: 'Hitachi',
      model: 'ZX200-5G',
      year: 2025,
      condition: 'new',
      status: 'in_stock',
      location: 'Surabaya Warehouse',
      unit: 'pcs',
      price: '380000000.00',
      currency: 'IDR',
      supplierId: supplierIds.supplier2,
      isActive: true,
    },
    {
      id: productIds.product14,
      code: 'VOL-1749458225471-652',
      name: 'Volvo EC200D',
      description: 'Crawler excavator for construction and material handling',
      category: 'excavator',
      brand: 'Volvo',
      model: 'EC200D',
      year: 2022,
      condition: 'used',
      status: 'in_stock',
      location: 'Jakarta Warehouse',
      unit: 'pcs',
      price: '320000000.00',
      currency: 'IDR',
      supplierId: supplierIds.supplier1,
      isActive: true,
    },
    {
      id: productIds.product15,
      code: 'JCB-1749458225471-653',
      name: 'JCB 3DX',
      description: 'Backhoe loader for versatile construction applications',
      category: 'backhoe_loader',
      brand: 'JCB',
      model: '3DX',
      year: 2025,
      condition: 'new',
      status: 'reserved',
      location: 'Surabaya Warehouse',
      unit: 'pcs',
      price: '320000000.00',
      currency: 'IDR',
      supplierId: supplierIds.supplier3,
      isActive: true,
    },
    {
      id: productIds.product16,
      code: 'CAT-1749458225471-654',
      name: 'Caterpillar 950K',
      description: 'Wheel loader for heavy-duty material handling',
      category: 'wheel_loader',
      brand: 'Caterpillar',
      model: '950K',
      year: 2024,
      condition: 'new',
      status: 'in_stock',
      location: 'Jakarta Warehouse',
      unit: 'pcs',
      price: '450000000.00',
      currency: 'IDR',
      supplierId: supplierIds.supplier2,
      isActive: true,
    },
    {
      id: productIds.product17,
      code: 'KOM-1749458225471-655',
      name: 'Komatsu D65PX-18',
      description: 'Bulldozer for earthmoving and construction',
      category: 'bulldozer',
      brand: 'Komatsu',
      model: 'D65PX-18',
      year: 2021,
      condition: 'used',
      status: 'in_stock',
      location: 'Surabaya Warehouse',
      unit: 'pcs',
      price: '280000000.00',
      currency: 'IDR',
      supplierId: supplierIds.supplier3,
      isActive: true,
    },
    {
      id: productIds.product18,
      code: 'HIT-1749458225471-656',
      name: 'Hitachi ZW310-6',
      description: 'Wheel loader for construction and material handling',
      category: 'wheel_loader',
      brand: 'Hitachi',
      model: 'ZW310-6',
      year: 2023,
      condition: 'used',
      status: 'maintenance',
      location: 'Jakarta Warehouse',
      unit: 'pcs',
      price: '220000000.00',
      currency: 'IDR',
      supplierId: supplierIds.supplier2,
      isActive: true,
    },
    {
      id: productIds.product19,
      code: 'VOL-1749458225471-657',
      name: 'Volvo L90H',
      description: 'Wheel loader for heavy construction applications',
      category: 'wheel_loader',
      brand: 'Volvo',
      model: 'L90H',
      year: 2025,
      condition: 'new',
      status: 'in_stock',
      location: 'Surabaya Warehouse',
      unit: 'pcs',
      price: '380000000.00',
      currency: 'IDR',
      supplierId: supplierIds.supplier1,
      isActive: true,
    },
    {
      id: productIds.product20,
      code: 'CAT-1749458225471-658',
      name: 'Caterpillar D6T',
      description: 'Bulldozer for earthmoving and construction',
      category: 'bulldozer',
      brand: 'Caterpillar',
      model: 'D6T',
      year: 2020,
      condition: 'used',
      status: 'in_stock',
      location: 'Jakarta Warehouse',
      unit: 'pcs',
      price: '350000000.00',
      currency: 'IDR',
      supplierId: supplierIds.supplier2,
      isActive: true,
    },
  ]);
  console.log('✅ Seeded 20 products');

  console.log('🔄 Seeding quotations...');
  await db.insert(schema.quotations).values([
    {
      id: quotationIds.quotation1,
      quotationNumber: 'QT/2025/04/001',
      quotationDate: new Date('2025-04-29'),
      validUntil: new Date('2025-07-29'),
      customerId: customerIds.customer1,
      approverId: userIds.user2, // Manager
      createdBy: userIds.user1,
      isIncludePPN: true,
      subtotal: '15000000.00',
      tax: '1500000.00',
      total: '16500000.00',
      currency: 'IDR',
      status: 'draft',
      notes: 'Standard quotation for heavy equipment',
      termsAndConditions: null,
    },
    {
      id: quotationIds.quotation2,
      quotationNumber: 'QT/2025/04/002',
      quotationDate: new Date('2025-04-29'),
      validUntil: new Date('2025-07-29'),
      customerId: customerIds.customer2,
      approverId: userIds.user3, // Director
      createdBy: userIds.user2,
      isIncludePPN: false,
      subtotal: '25000000.00',
      tax: '0.00',
      total: '25000000.00',
      currency: 'IDR',
      status: 'sent',
      notes: 'Special pricing for bulk order',
      termsAndConditions: null,
    },
    {
      id: quotationIds.quotation3,
      quotationNumber: 'QT/2025/05/001',
      quotationDate: new Date('2025-05-29'),
      validUntil: new Date('2025-07-29'),
      customerId: customerIds.customer3,
      approverId: userIds.user2, // Manager
      createdBy: userIds.user1,
      isIncludePPN: true,
      subtotal: '35000000.00',
      tax: '3500000.00',
      total: '38500000.00',
      currency: 'IDR',
      status: 'accepted',
      notes: 'Premium equipment package',
      termsAndConditions: null,
    },
    {
      id: quotationIds.quotation4,
      quotationNumber: 'QT/2025/06/001',
      quotationDate: new Date('2025-01-30'),
      validUntil: new Date('2025-02-28'),
      customerId: customerIds.customer4,
      approverId: userIds.user3, // Director
      createdBy: userIds.user3,
      isIncludePPN: true,
      subtotal: '18000000.00',
      tax: '1800000.00',
      total: '19800000.00',
      currency: 'IDR',
      status: 'rejected',
      notes: 'Budget constraints',
      termsAndConditions: null,
    },
    {
      id: quotationIds.quotation5,
      quotationNumber: 'QT/2025/06/002',
      quotationDate: new Date('2025-06-15'),
      validUntil: new Date('2025-07-15'),
      customerId: customerIds.customer5,
      approverId: userIds.user2, // Manager
      createdBy: userIds.user4,
      isIncludePPN: true,
      subtotal: '42000000.00',
      tax: '4200000.00',
      total: '46200000.00',
      currency: 'IDR',
      status: 'draft',
      notes: 'Caterpillar excavator for mining operations',
      termsAndConditions: null,
    },
    {
      id: quotationIds.quotation6,
      quotationNumber: 'QT/2025/06/003',
      quotationDate: new Date('2025-06-20'),
      validUntil: new Date('2025-07-20'),
      customerId: customerIds.customer1,
      approverId: userIds.user3, // Director
      createdBy: userIds.user2,
      isIncludePPN: false,
      subtotal: '28000000.00',
      tax: '0.00',
      total: '28000000.00',
      currency: 'IDR',
      status: 'sent',
      notes: 'Komatsu excavator for infrastructure project',
      termsAndConditions: null,
    },
    {
      id: quotationIds.quotation7,
      quotationNumber: 'QT/2025/09/001',
      quotationDate: new Date('2025-09-10'),
      validUntil: new Date('2025-12-10'),
      customerId: customerIds.customer2,
      approverId: userIds.user2, // Manager
      createdBy: userIds.user1,
      isIncludePPN: true,
      subtotal: '32000000.00',
      tax: '3200000.00',
      total: '35200000.00',
      currency: 'IDR',
      status: 'accepted',
      notes: 'JCB backhoe loader for construction site',
      termsAndConditions: null,
    },
    {
      id: quotationIds.quotation8,
      quotationNumber: 'QT/2025/10/001',
      quotationDate: new Date('2025-10-15'),
      validUntil: new Date('2025-11-15'),
      customerId: customerIds.customer3,
      approverId: userIds.user2, // Manager
      createdBy: userIds.user1,
      isIncludePPN: true,
      subtotal: '45000000.00',
      tax: '4500000.00',
      total: '49500000.00',
      currency: 'IDR',
      status: 'sent',
      notes: 'Hitachi excavator for large construction project',
      termsAndConditions: null,
    },
    {
      id: quotationIds.quotation9,
      quotationNumber: 'QT/2025/10/002',
      quotationDate: new Date('2025-10-20'),
      validUntil: new Date('2025-11-20'),
      customerId: customerIds.customer4,
      approverId: userIds.user3, // Director
      createdBy: userIds.user2,
      isIncludePPN: false,
      subtotal: '22000000.00',
      tax: '0.00',
      total: '22000000.00',
      currency: 'IDR',
      status: 'sent',
      notes: 'Volvo wheel loader for logistics center',
      termsAndConditions: null,
    },
  ]);
  console.log('✅ Seeded 9 quotations');

  console.log('🔄 Seeding quotation items...');
  await db.insert(schema.quotationItems).values([
    {
      id: randomUUID(),
      quotationId: quotationIds.quotation1,
      productId: productIds.product1,
      quantity: '1.00',
      unitPrice: '15000000.00',
      total: '15000000.00',
      notes: 'Wheel loader with standard configuration',
    },
    {
      id: randomUUID(),
      quotationId: quotationIds.quotation2,
      productId: productIds.product2,
      quantity: '1.00',
      unitPrice: '25000000.00',
      total: '25000000.00',
      notes: 'Wheel loader with premium features',
    },
    {
      id: randomUUID(),
      quotationId: quotationIds.quotation3,
      productId: productIds.product4,
      quantity: '1.00',
      unitPrice: '35000000.00',
      total: '35000000.00',
      notes: 'Bulldozer with advanced controls',
    },
    {
      id: randomUUID(),
      quotationId: quotationIds.quotation4,
      productId: productIds.product5,
      quantity: '1.00',
      unitPrice: '18000000.00',
      total: '18000000.00',
      notes: 'Excavator for construction project',
    },
    {
      id: randomUUID(),
      quotationId: quotationIds.quotation5,
      productId: productIds.product11,
      quantity: '1.00',
      unitPrice: '42000000.00',
      total: '42000000.00',
      notes: 'Caterpillar excavator for mining operations',
    },
    {
      id: randomUUID(),
      quotationId: quotationIds.quotation6,
      productId: productIds.product12,
      quantity: '1.00',
      unitPrice: '28000000.00',
      total: '28000000.00',
      notes: 'Komatsu excavator for infrastructure project',
    },
    {
      id: randomUUID(),
      quotationId: quotationIds.quotation7,
      productId: productIds.product15,
      quantity: '1.00',
      unitPrice: '32000000.00',
      total: '32000000.00',
      notes: 'JCB backhoe loader for construction site',
    },
    {
      id: randomUUID(),
      quotationId: quotationIds.quotation8,
      productId: productIds.product13,
      quantity: '1.00',
      unitPrice: '45000000.00',
      total: '45000000.00',
      notes: 'Hitachi excavator for large construction project',
    },
    {
      id: randomUUID(),
      quotationId: quotationIds.quotation9,
      productId: productIds.product14,
      quantity: '1.00',
      unitPrice: '22000000.00',
      total: '22000000.00',
      notes: 'Volvo wheel loader for logistics center',
    },
  ]);
  console.log('✅ Seeded 9 quotation items');

  console.log('🔄 Seeding invoices...');
  await db.insert(schema.invoices).values([
    {
      id: invoiceIds.invoice1,
      invoiceNumber: 'INV/2025/04/001',
      quotationId: quotationIds.quotation3, // Accepted quotation
      invoiceDate: new Date('2025-04-30'),
      dueDate: new Date('2025-05-30'),
      customerId: customerIds.customer3,
      subtotal: '35000000.00',
      tax: '3500000.00',
      total: '38500000.00',
      currency: 'IDR',
      status: 'paid',
      paymentMethod: 'Bank Transfer',
      notes: 'Invoice for premium equipment package - payment received',
      createdBy: userIds.user1,
    },
    {
      id: invoiceIds.invoice2,
      invoiceNumber: 'INV/2025/06/001',
      quotationId: quotationIds.quotation7, // Accepted quotation
      invoiceDate: new Date('2025-06-20'),
      dueDate: new Date('2025-07-20'),
      customerId: customerIds.customer2,
      subtotal: '32000000.00',
      tax: '3200000.00',
      total: '35200000.00',
      currency: 'IDR',
      status: 'sent',
      paymentMethod: 'Bank Transfer',
      notes: 'Invoice for JCB backhoe loader - pending payment',
      createdBy: userIds.user2,
    },
    {
      id: invoiceIds.invoice3,
      invoiceNumber: 'INV/2025/07/001',
      quotationId: null, // Direct invoice without quotation
      invoiceDate: new Date('2025-07-15'),
      dueDate: new Date('2025-08-15'),
      customerId: customerIds.customer1,
      subtotal: '18500000.00',
      tax: '1850000.00',
      total: '20350000.00',
      currency: 'IDR',
      status: 'draft',
      paymentMethod: 'Bank Transfer',
      notes: 'Direct invoice for Shantui wheel loader',
      createdBy: userIds.user1,
    },
    {
      id: invoiceIds.invoice4,
      invoiceNumber: 'INV/2025/08/001',
      quotationId: null, // Direct invoice without quotation
      invoiceDate: new Date('2025-08-10'),
      dueDate: new Date('2025-09-10'),
      customerId: customerIds.customer4,
      subtotal: '22000000.00',
      tax: '0.00',
      total: '22000000.00',
      currency: 'IDR',
      status: 'sent',
      paymentMethod: 'Cash',
      notes: 'Direct invoice for bulldozer - no PPN',
      createdBy: userIds.user4,
    },
    {
      id: invoiceIds.invoice5,
      invoiceNumber: 'INV/2025/09/001',
      quotationId: null, // Direct invoice without quotation
      invoiceDate: new Date('2025-09-05'),
      dueDate: new Date('2025-10-05'),
      customerId: customerIds.customer5,
      subtotal: '42000000.00',
      tax: '4200000.00',
      total: '46200000.00',
      currency: 'IDR',
      status: 'paid',
      paymentMethod: 'Bank Transfer',
      notes: 'Direct invoice for Caterpillar excavator - payment received',
      createdBy: userIds.user2,
    },
    {
      id: invoiceIds.invoice6,
      invoiceNumber: 'INV/2025/10/001',
      quotationId: null, // Direct invoice without quotation
      invoiceDate: new Date('2025-10-01'),
      dueDate: new Date('2025-11-01'),
      customerId: customerIds.customer3,
      subtotal: '13500000.00',
      tax: '1350000.00',
      total: '14850000.00',
      currency: 'IDR',
      status: 'void',
      paymentMethod: 'Bank Transfer',
      notes: 'Voided invoice due to customer cancellation',
      createdBy: userIds.user1,
    },
  ]);
  console.log('✅ Seeded 6 invoices');

  console.log('🔄 Seeding invoice items...');
  await db.insert(schema.invoiceItems).values([
    {
      id: randomUUID(),
      invoiceId: invoiceIds.invoice1,
      productId: productIds.product4,
      quantity: '1.00',
      unitPrice: '35000000.00',
      total: '35000000.00',
      paymentTerms: 'NET 30',
      termsAndConditions: 'Standard payment terms apply',
      notes: 'Bulldozer with advanced controls - fully paid',
    },
    {
      id: randomUUID(),
      invoiceId: invoiceIds.invoice2,
      productId: productIds.product15,
      quantity: '1.00',
      unitPrice: '32000000.00',
      total: '32000000.00',
      paymentTerms: 'NET 30',
      termsAndConditions: 'Payment due within 30 days',
      notes: 'JCB backhoe loader for construction site',
    },
    {
      id: randomUUID(),
      invoiceId: invoiceIds.invoice3,
      productId: productIds.product1,
      quantity: '1.00',
      unitPrice: '18500000.00',
      total: '18500000.00',
      paymentTerms: 'NET 30',
      termsAndConditions: 'Standard terms and conditions',
      notes: 'Shantui wheel loader - direct sale',
    },
    {
      id: randomUUID(),
      invoiceId: invoiceIds.invoice4,
      productId: productIds.product8,
      quantity: '1.00',
      unitPrice: '22000000.00',
      total: '22000000.00',
      paymentTerms: 'NET 15',
      termsAndConditions: 'Cash payment preferred',
      notes: 'Shantui bulldozer - no PPN applied',
    },
    {
      id: randomUUID(),
      invoiceId: invoiceIds.invoice5,
      productId: productIds.product11,
      quantity: '1.00',
      unitPrice: '42000000.00',
      total: '42000000.00',
      paymentTerms: 'NET 30',
      termsAndConditions: 'Premium equipment warranty included',
      notes: 'Caterpillar excavator - payment received',
    },
    {
      id: randomUUID(),
      invoiceId: invoiceIds.invoice6,
      productId: productIds.product6,
      quantity: '1.00',
      unitPrice: '13500000.00',
      total: '13500000.00',
      paymentTerms: 'NET 30',
      termsAndConditions: 'Standard terms apply',
      notes: 'Shantui compactor - voided due to cancellation',
    },
  ]);
  console.log('✅ Seeded 6 invoice items');

  console.log('🔄 Seeding delivery notes...');
  await db.insert(schema.deliveryNotes).values([
    {
      id: deliveryNoteIds.deliveryNote1,
      deliveryNumber: 'DN/2025/05/001',
      invoiceId: invoiceIds.invoice1, // Paid invoice
      customerId: customerIds.customer3,
      deliveryDate: new Date('2025-05-05'),
      deliveryMethod: 'Truck Delivery',
      driverName: 'Ahmad Supriadi',
      vehicleNumber: 'B 1234 ABC',
      status: 'delivered',
      deliveredBy: userIds.user1,
      receivedBy: userIds.user3, // Customer representative
      notes: 'Bulldozer delivered successfully to construction site',
      createdBy: userIds.user1,
    },
    {
      id: deliveryNoteIds.deliveryNote2,
      deliveryNumber: 'DN/2025/07/001',
      invoiceId: invoiceIds.invoice2, // Sent invoice
      customerId: customerIds.customer2,
      deliveryDate: new Date('2025-07-25'),
      deliveryMethod: 'Truck Delivery',
      driverName: 'Budi Santoso',
      vehicleNumber: 'B 5678 DEF',
      status: 'pending',
      deliveredBy: null,
      receivedBy: null,
      notes: 'JCB backhoe loader scheduled for delivery',
      createdBy: userIds.user2,
    },
    {
      id: deliveryNoteIds.deliveryNote3,
      deliveryNumber: 'DN/2025/09/001',
      invoiceId: invoiceIds.invoice5, // Paid invoice
      customerId: customerIds.customer5,
      deliveryDate: new Date('2025-09-10'),
      deliveryMethod: 'Truck Delivery',
      driverName: 'Rizky Pratama',
      vehicleNumber: 'B 9012 GHI',
      status: 'delivered',
      deliveredBy: userIds.user2,
      receivedBy: userIds.user4, // Customer representative
      notes: 'Caterpillar excavator delivered to mining site',
      createdBy: userIds.user2,
    },
    {
      id: deliveryNoteIds.deliveryNote4,
      deliveryNumber: 'DN/2025/08/001',
      invoiceId: invoiceIds.invoice4, // Sent invoice
      customerId: customerIds.customer4,
      deliveryDate: new Date('2025-08-15'),
      deliveryMethod: 'Customer Pickup',
      driverName: null,
      vehicleNumber: null,
      status: 'delivered',
      deliveredBy: userIds.user4,
      receivedBy: userIds.user1, // Customer representative
      notes: 'Bulldozer picked up by customer at warehouse',
      createdBy: userIds.user4,
    },
  ]);
  console.log('✅ Seeded 4 delivery notes');

  console.log('🔄 Seeding delivery note items...');
  await db.insert(schema.deliveryNoteItems).values([
    {
      id: randomUUID(),
      deliveryNoteId: deliveryNoteIds.deliveryNote1,
      productId: productIds.product4,
      quantity: '1.00',
      deliveredQuantity: '1.00',
      notes: 'Shantui DH08-B3-XL bulldozer delivered with full accessories',
    },
    {
      id: randomUUID(),
      deliveryNoteId: deliveryNoteIds.deliveryNote2,
      productId: productIds.product15,
      quantity: '1.00',
      deliveredQuantity: '0.00',
      notes: 'JCB 3DX backhoe loader - pending delivery',
    },
    {
      id: randomUUID(),
      deliveryNoteId: deliveryNoteIds.deliveryNote3,
      productId: productIds.product11,
      quantity: '1.00',
      deliveredQuantity: '1.00',
      notes: 'Caterpillar 320 excavator delivered with operator training',
    },
    {
      id: randomUUID(),
      deliveryNoteId: deliveryNoteIds.deliveryNote4,
      productId: productIds.product8,
      quantity: '1.00',
      deliveredQuantity: '1.00',
      notes: 'Shantui SD16F bulldozer picked up by customer',
    },
  ]);
  console.log('✅ Seeded 4 delivery note items');

  await connection.end();
  console.log('🎉 Database seeded successfully with complete sample data!');
}

main().catch((error) => {
  console.error('❌ Error seeding database:', error);
  process.exit(1);
});
