services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: bizdocgen-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bizdocgen
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - bizdocgen-network
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10

  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bizdocgen-app
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=bizdocgen
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - bizdocgen-network
    volumes:
      - ./uploads:/app/uploads
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/api/health']
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mysql_data:
    driver: local

networks:
  bizdocgen-network:
    driver: bridge
