import { roleIds } from './roles';
import { userIds } from './users';

export const permissionIds = {
  users: {
    read: 'users:read',
    create: 'users:create',
    update: 'users:update',
    delete: 'users:delete',
  },
  branches: {
    read: 'branches:read',
    create: 'branches:create',
    update: 'branches:update',
    delete: 'branches:delete',
  },
  roles: {
    read: 'roles:read',
    create: 'roles:create',
    update: 'roles:update',
    delete: 'roles:delete',
  },
  quotations: {
    read: 'quotations:read',
    create: 'quotations:create',
    update: 'quotations:update',
    delete: 'quotations:delete',
    approve: 'quotations:approve',
  },
  invoices: {
    read: 'invoices:read',
    create: 'invoices:create',
    update: 'invoices:update',
    delete: 'invoices:delete',
  },
  deliveries: {
    read: 'deliveries:read',
    create: 'deliveries:create',
    update: 'deliveries:update',
    delete: 'deliveries:delete',
  },
  imports: {
    read: 'imports:read',
    create: 'imports:create',
    update: 'imports:update',
    delete: 'imports:delete',
    approve: 'imports:approve',
  },
  products: {
    read: 'products:read',
    create: 'products:create',
    update: 'products:update',
    delete: 'products:delete',
  },
  suppliers: {
    read: 'suppliers:read',
    create: 'suppliers:create',
    update: 'suppliers:update',
    delete: 'suppliers:delete',
  },
  customers: {
    read: 'customers:read',
    create: 'customers:create',
    update: 'customers:update',
    delete: 'customers:delete',
  },
  warehouses: {
    read: 'warehouses:read',
    create: 'warehouses:create',
    update: 'warehouses:update',
    delete: 'warehouses:delete',
  },
  transfers: {
    read: 'transfers:read',
    create: 'transfers:create',
    update: 'transfers:update',
    delete: 'transfers:delete',
  },
  masterData: {
    read: 'master-data:read',
    create: 'master-data:create',
    update: 'master-data:update',
    delete: 'master-data:delete',
  },
};

export const permissions = [
  {
    id: permissionIds.users.read,
    name: 'users:read',
    description: 'View and read user accounts',
    resources: 'users',
    actions: 'read',
  },
  {
    id: permissionIds.users.create,
    name: 'users:create',
    description: 'Create new user accounts',
    resources: 'users',
    actions: 'create',
  },
  {
    id: permissionIds.users.update,
    name: 'users:update',
    description: 'Edit and update user accounts',
    resources: 'users',
    actions: 'update',
  },
  {
    id: permissionIds.users.delete,
    name: 'users:delete',
    description: 'Delete user accounts',
    resources: 'users',
    actions: 'delete',
  },
  {
    id: permissionIds.branches.read,
    name: 'branches:read',
    description: 'View and read branch information',
    resources: 'branches',
    actions: 'read',
  },
  {
    id: permissionIds.branches.create,
    name: 'branches:create',
    description: 'Create new branches',
    resources: 'branches',
    actions: 'create',
  },
  {
    id: permissionIds.branches.update,
    name: 'branches:update',
    description: 'Edit and update branch information',
    resources: 'branches',
    actions: 'update',
  },
  {
    id: permissionIds.branches.delete,
    name: 'branches:delete',
    description: 'Delete branches',
    resources: 'branches',
    actions: 'delete',
  },
  {
    id: permissionIds.quotations.read,
    name: 'quotations:read',
    description: 'View and read quotations',
    resources: 'quotations',
    actions: 'read',
  },
  {
    id: permissionIds.quotations.create,
    name: 'quotations:create',
    description: 'Create new quotations',
    resources: 'quotations',
    actions: 'create',
  },
  {
    id: permissionIds.quotations.update,
    name: 'quotations:update',
    description: 'Edit and update quotations',
    resources: 'quotations',
    actions: 'update',
  },
  {
    id: permissionIds.quotations.delete,
    name: 'quotations:delete',
    description: 'Delete quotations',
    resources: 'quotations',
    actions: 'delete',
  },
  {
    id: permissionIds.quotations.approve,
    name: 'quotations:approve',
    description: 'Approve quotations',
    resources: 'quotations',
    actions: 'approve',
  },
  {
    id: permissionIds.invoices.read,
    name: 'invoices:read',
    description: 'View and read invoices',
    resources: 'invoices',
    actions: 'read',
  },
  {
    id: permissionIds.invoices.create,
    name: 'invoices:create',
    description: 'Create new invoices',
    resources: 'invoices',
    actions: 'create',
  },
  {
    id: permissionIds.invoices.update,
    name: 'invoices:update',
    description: 'Edit and update invoices',
    resources: 'invoices',
    actions: 'update',
  },
  {
    id: permissionIds.invoices.delete,
    name: 'invoices:delete',
    description: 'Delete invoices',
    resources: 'invoices',
    actions: 'delete',
  },
  {
    id: permissionIds.deliveries.read,
    name: 'deliveries:read',
    description: 'View and read delivery notes',
    resources: 'deliveries',
    actions: 'read',
  },
  {
    id: permissionIds.deliveries.create,
    name: 'deliveries:create',
    description: 'Create new delivery notes',
    resources: 'deliveries',
    actions: 'create',
  },
  {
    id: permissionIds.deliveries.update,
    name: 'deliveries:update',
    description: 'Edit and update delivery notes',
    resources: 'deliveries',
    actions: 'update',
  },
  {
    id: permissionIds.deliveries.delete,
    name: 'deliveries:delete',
    description: 'Delete delivery notes',
    resources: 'deliveries',
    actions: 'delete',
  },
  {
    id: permissionIds.imports.read,
    name: 'imports:read',
    description: 'View and read import records',
    resources: 'imports',
    actions: 'read',
  },
  {
    id: permissionIds.imports.create,
    name: 'imports:create',
    description: 'Create new import records',
    resources: 'imports',
    actions: 'create',
  },
  {
    id: permissionIds.imports.update,
    name: 'imports:update',
    description: 'Edit and update import records',
    resources: 'imports',
    actions: 'update',
  },
  {
    id: permissionIds.imports.delete,
    name: 'imports:delete',
    description: 'Delete import records',
    resources: 'imports',
    actions: 'delete',
  },
  {
    id: permissionIds.imports.approve,
    name: 'imports:approve',
    description: 'Verify and approve imports',
    resources: 'imports',
    actions: 'approve',
  },
  {
    id: permissionIds.products.read,
    name: 'products:read',
    description: 'View and read product catalog',
    resources: 'products',
    actions: 'read',
  },
  {
    id: permissionIds.products.create,
    name: 'products:create',
    description: 'Create new products',
    resources: 'products',
    actions: 'create',
  },
  {
    id: permissionIds.products.update,
    name: 'products:update',
    description: 'Edit and update products',
    resources: 'products',
    actions: 'update',
  },
  {
    id: permissionIds.products.delete,
    name: 'products:delete',
    description: 'Delete products',
    resources: 'products',
    actions: 'delete',
  },
  {
    id: permissionIds.suppliers.read,
    name: 'suppliers:read',
    description: 'View and read supplier information',
    resources: 'suppliers',
    actions: 'read',
  },
  {
    id: permissionIds.suppliers.create,
    name: 'suppliers:create',
    description: 'Create new suppliers',
    resources: 'suppliers',
    actions: 'create',
  },
  {
    id: permissionIds.suppliers.update,
    name: 'suppliers:update',
    description: 'Edit and update suppliers',
    resources: 'suppliers',
    actions: 'update',
  },
  {
    id: permissionIds.suppliers.delete,
    name: 'suppliers:delete',
    description: 'Delete suppliers',
    resources: 'suppliers',
    actions: 'delete',
  },
  {
    id: permissionIds.customers.read,
    name: 'customers:read',
    description: 'View and read customer information',
    resources: 'customers',
    actions: 'read',
  },
  {
    id: permissionIds.customers.create,
    name: 'customers:create',
    description: 'Create new customers',
    resources: 'customers',
    actions: 'create',
  },
  {
    id: permissionIds.customers.update,
    name: 'customers:update',
    description: 'Edit and update customers',
    resources: 'customers',
    actions: 'update',
  },
  {
    id: permissionIds.customers.delete,
    name: 'customers:delete',
    description: 'Delete customers',
    resources: 'customers',
    actions: 'delete',
  },
  {
    id: permissionIds.warehouses.read,
    name: 'warehouses:read',
    description: 'View and read warehouse information',
    resources: 'warehouses',
    actions: 'read',
  },
  {
    id: permissionIds.warehouses.create,
    name: 'warehouses:create',
    description: 'Create new warehouses',
    resources: 'warehouses',
    actions: 'create',
  },
  {
    id: permissionIds.warehouses.update,
    name: 'warehouses:update',
    description: 'Edit and update warehouses',
    resources: 'warehouses',
    actions: 'update',
  },
  {
    id: permissionIds.warehouses.delete,
    name: 'warehouses:delete',
    description: 'Delete warehouses',
    resources: 'warehouses',
    actions: 'delete',
  },
  {
    id: permissionIds.transfers.read,
    name: 'transfers:read',
    description: 'View and read stock transfers',
    resources: 'transfers',
    actions: 'read',
  },
  {
    id: permissionIds.transfers.create,
    name: 'transfers:create',
    description: 'Create new stock transfers',
    resources: 'transfers',
    actions: 'create',
  },
  {
    id: permissionIds.transfers.update,
    name: 'transfers:update',
    description: 'Edit and update stock transfers',
    resources: 'transfers',
    actions: 'update',
  },
  {
    id: permissionIds.transfers.delete,
    name: 'transfers:delete',
    description: 'Delete stock transfers',
    resources: 'transfers',
    actions: 'delete',
  },
  {
    id: permissionIds.roles.read,
    name: 'roles:read',
    description: 'View and read user roles',
    resources: 'roles',
    actions: 'read',
  },
  {
    id: permissionIds.roles.create,
    name: 'roles:create',
    description: 'Create new user roles',
    resources: 'roles',
    actions: 'create',
  },
  {
    id: permissionIds.roles.update,
    name: 'roles:update',
    description: 'Edit and update user roles',
    resources: 'roles',
    actions: 'update',
  },
  {
    id: permissionIds.roles.delete,
    name: 'roles:delete',
    description: 'Delete user roles',
    resources: 'roles',
    actions: 'delete',
  },
  {
    id: permissionIds.masterData.read,
    name: 'master-data:read',
    description: 'View and read master data',
    resources: 'master-data',
    actions: 'read',
  },
  {
    id: permissionIds.masterData.create,
    name: 'master-data:create',
    description: 'Create new master data entries',
    resources: 'master-data',
    actions: 'create',
  },
  {
    id: permissionIds.masterData.update,
    name: 'master-data:update',
    description: 'Edit and update master data entries',
    resources: 'master-data',
    actions: 'update',
  },
  {
    id: permissionIds.masterData.delete,
    name: 'master-data:delete',
    description: 'Delete master data entries',
    resources: 'master-data',
    actions: 'delete',
  },
];

// Complete role permissions mapping
export const rolePermissions = [
  // Admin - Full permissions for everything
  { roleId: roleIds.admin, permissionId: permissionIds.users.read },
  { roleId: roleIds.admin, permissionId: permissionIds.users.create },
  { roleId: roleIds.admin, permissionId: permissionIds.users.update },
  { roleId: roleIds.admin, permissionId: permissionIds.users.delete },
  { roleId: roleIds.admin, permissionId: permissionIds.branches.read },
  { roleId: roleIds.admin, permissionId: permissionIds.branches.create },
  { roleId: roleIds.admin, permissionId: permissionIds.branches.update },
  { roleId: roleIds.admin, permissionId: permissionIds.branches.delete },
  { roleId: roleIds.admin, permissionId: permissionIds.roles.read },
  { roleId: roleIds.admin, permissionId: permissionIds.roles.create },
  { roleId: roleIds.admin, permissionId: permissionIds.roles.update },
  { roleId: roleIds.admin, permissionId: permissionIds.roles.delete },
  { roleId: roleIds.admin, permissionId: permissionIds.quotations.read },
  { roleId: roleIds.admin, permissionId: permissionIds.quotations.create },
  { roleId: roleIds.admin, permissionId: permissionIds.quotations.update },
  { roleId: roleIds.admin, permissionId: permissionIds.quotations.delete },
  { roleId: roleIds.admin, permissionId: permissionIds.quotations.approve },
  { roleId: roleIds.admin, permissionId: permissionIds.invoices.read },
  { roleId: roleIds.admin, permissionId: permissionIds.invoices.create },
  { roleId: roleIds.admin, permissionId: permissionIds.invoices.update },
  { roleId: roleIds.admin, permissionId: permissionIds.invoices.delete },
  { roleId: roleIds.admin, permissionId: permissionIds.deliveries.read },
  { roleId: roleIds.admin, permissionId: permissionIds.deliveries.create },
  { roleId: roleIds.admin, permissionId: permissionIds.deliveries.update },
  { roleId: roleIds.admin, permissionId: permissionIds.deliveries.delete },
  { roleId: roleIds.admin, permissionId: permissionIds.imports.read },
  { roleId: roleIds.admin, permissionId: permissionIds.imports.create },
  { roleId: roleIds.admin, permissionId: permissionIds.imports.update },
  { roleId: roleIds.admin, permissionId: permissionIds.imports.delete },
  { roleId: roleIds.admin, permissionId: permissionIds.imports.approve },
  { roleId: roleIds.admin, permissionId: permissionIds.products.read },
  { roleId: roleIds.admin, permissionId: permissionIds.products.create },
  { roleId: roleIds.admin, permissionId: permissionIds.products.update },
  { roleId: roleIds.admin, permissionId: permissionIds.products.delete },
  { roleId: roleIds.admin, permissionId: permissionIds.suppliers.read },
  { roleId: roleIds.admin, permissionId: permissionIds.suppliers.create },
  { roleId: roleIds.admin, permissionId: permissionIds.suppliers.update },
  { roleId: roleIds.admin, permissionId: permissionIds.suppliers.delete },
  { roleId: roleIds.admin, permissionId: permissionIds.customers.read },
  { roleId: roleIds.admin, permissionId: permissionIds.customers.create },
  { roleId: roleIds.admin, permissionId: permissionIds.customers.update },
  { roleId: roleIds.admin, permissionId: permissionIds.customers.delete },
  { roleId: roleIds.admin, permissionId: permissionIds.warehouses.read },
  { roleId: roleIds.admin, permissionId: permissionIds.warehouses.create },
  { roleId: roleIds.admin, permissionId: permissionIds.warehouses.update },
  { roleId: roleIds.admin, permissionId: permissionIds.warehouses.delete },
  { roleId: roleIds.admin, permissionId: permissionIds.transfers.read },
  { roleId: roleIds.admin, permissionId: permissionIds.transfers.create },
  { roleId: roleIds.admin, permissionId: permissionIds.transfers.update },
  { roleId: roleIds.admin, permissionId: permissionIds.transfers.delete },
  { roleId: roleIds.admin, permissionId: permissionIds.masterData.read },
  { roleId: roleIds.admin, permissionId: permissionIds.masterData.create },
  { roleId: roleIds.admin, permissionId: permissionIds.masterData.update },
  { roleId: roleIds.admin, permissionId: permissionIds.masterData.delete },

  // Manager - Business operations permissions
  { roleId: roleIds.manager, permissionId: permissionIds.quotations.read },
  { roleId: roleIds.manager, permissionId: permissionIds.quotations.create },
  { roleId: roleIds.manager, permissionId: permissionIds.quotations.update },
  { roleId: roleIds.manager, permissionId: permissionIds.quotations.approve },
  { roleId: roleIds.manager, permissionId: permissionIds.invoices.read },
  { roleId: roleIds.manager, permissionId: permissionIds.invoices.create },
  { roleId: roleIds.manager, permissionId: permissionIds.invoices.update },
  { roleId: roleIds.manager, permissionId: permissionIds.deliveries.read },
  { roleId: roleIds.manager, permissionId: permissionIds.deliveries.create },
  { roleId: roleIds.manager, permissionId: permissionIds.deliveries.update },
  { roleId: roleIds.manager, permissionId: permissionIds.products.read },
  { roleId: roleIds.manager, permissionId: permissionIds.products.create },
  { roleId: roleIds.manager, permissionId: permissionIds.products.update },
  { roleId: roleIds.manager, permissionId: permissionIds.suppliers.read },
  { roleId: roleIds.manager, permissionId: permissionIds.customers.read },
  { roleId: roleIds.manager, permissionId: permissionIds.customers.create },
  { roleId: roleIds.manager, permissionId: permissionIds.customers.update },
  { roleId: roleIds.manager, permissionId: permissionIds.warehouses.read },
  { roleId: roleIds.manager, permissionId: permissionIds.transfers.read },
  { roleId: roleIds.manager, permissionId: permissionIds.transfers.create },
  { roleId: roleIds.manager, permissionId: permissionIds.transfers.update },

  // Import Manager - Import and warehouse management
  { roleId: roleIds.importManager, permissionId: permissionIds.imports.read },
  { roleId: roleIds.importManager, permissionId: permissionIds.imports.create },
  { roleId: roleIds.importManager, permissionId: permissionIds.imports.update },
  {
    roleId: roleIds.importManager,
    permissionId: permissionIds.imports.approve,
  },
  { roleId: roleIds.importManager, permissionId: permissionIds.products.read },
  {
    roleId: roleIds.importManager,
    permissionId: permissionIds.products.create,
  },
  {
    roleId: roleIds.importManager,
    permissionId: permissionIds.products.update,
  },
  { roleId: roleIds.importManager, permissionId: permissionIds.suppliers.read },
  {
    roleId: roleIds.importManager,
    permissionId: permissionIds.warehouses.read,
  },
  { roleId: roleIds.importManager, permissionId: permissionIds.transfers.read },
  {
    roleId: roleIds.importManager,
    permissionId: permissionIds.transfers.create,
  },
  {
    roleId: roleIds.importManager,
    permissionId: permissionIds.transfers.update,
  },

  // Director - High-level approvals and reports
  { roleId: roleIds.director, permissionId: permissionIds.quotations.read },
  { roleId: roleIds.director, permissionId: permissionIds.quotations.approve },
  { roleId: roleIds.director, permissionId: permissionIds.invoices.read },
  { roleId: roleIds.director, permissionId: permissionIds.deliveries.read },
  { roleId: roleIds.director, permissionId: permissionIds.imports.read },
  { roleId: roleIds.director, permissionId: permissionIds.products.read },
  { roleId: roleIds.director, permissionId: permissionIds.suppliers.read },
  { roleId: roleIds.director, permissionId: permissionIds.customers.read },
  { roleId: roleIds.director, permissionId: permissionIds.warehouses.read },
  { roleId: roleIds.director, permissionId: permissionIds.transfers.read },

  // Staff - Limited read permissions
  { roleId: roleIds.staff, permissionId: permissionIds.quotations.read },
  { roleId: roleIds.staff, permissionId: permissionIds.quotations.create },
  { roleId: roleIds.staff, permissionId: permissionIds.invoices.read },
  { roleId: roleIds.staff, permissionId: permissionIds.deliveries.read },
  { roleId: roleIds.staff, permissionId: permissionIds.products.read },
  { roleId: roleIds.staff, permissionId: permissionIds.suppliers.read },
  { roleId: roleIds.staff, permissionId: permissionIds.customers.read },
  { roleId: roleIds.staff, permissionId: permissionIds.warehouses.read },
];

// Complete user role assignments
export const userRoles = [
  {
    userId: userIds.admin_ho_jakarta,
    roleId: roleIds.admin,
  },
  {
    userId: userIds.manager_kendari,
    roleId: roleIds.manager,
  },
  {
    userId: userIds.staff_pekanbaru,
    roleId: roleIds.staff,
  },
  {
    userId: userIds.user4, // Director
    roleId: roleIds.director,
  },
  {
    userId: userIds.user5, // Staff
    roleId: roleIds.staff,
  },
  {
    userId: userIds.user6, // Import Manager
    roleId: roleIds.importManager,
  },
  {
    userId: userIds.user7, // Inactive Staff
    roleId: roleIds.staff,
  },
];
