import { PRODUCT_CATEGORY } from '../enum';
import { products as productsSchema } from '../schema';
import { productIds, supplierIds, warehouseIds } from './seed-constants';

export type NewProduct = typeof productsSchema.$inferInsert;

export const products: NewProduct[] = [
  {
    id: productIds.product1,
    name: 'Shantui L36-B3 Wheel Loader',
    description: 'Wheel Loader for construction and material handling',
    category: PRODUCT_CATEGORY.SERIALIZED,
    machineTypeId: 'wheelLoader',
    unitOfMeasureId: 'pcs',
    brandId: 'shantui',
    model: 'L36-B3',
    serialNumber: 'SHA-L36B3-2025-001',
    machineNumber: 'WL-2025-001',
    year: 2025,
    condition: 'new',
    status: 'in_stock',
    price: '185000000.00',
    engineModel: 'WD10G220E23',
    enginePower: '220 hp',
    operatingWeight: '18,500 kg',
    warehouseId: warehouseIds.warehouse1,
    supplierId: supplierIds.supplier1,
    isActive: true,
  },
  {
    id: productIds.product2,
    name: 'Shantui L36-B3 Wheel Loader',
    description: 'Wheel Loader for construction and material handling',
    category: PRODUCT_CATEGORY.SERIALIZED,
    machineTypeId: 'wheelLoader',
    unitOfMeasureId: 'pcs',
    brandId: 'shantui',
    model: 'L36-B3',
    serialNumber: 'SHA-L36B3-2023-002',
    machineNumber: 'WL-2023-002',
    year: 2023,
    condition: 'used',
    status: 'reserved',
    price: '145000000.00',
    engineModel: 'WD10G220E23',
    enginePower: '220 hp',
    operatingWeight: '18,500 kg',
    warehouseId: warehouseIds.warehouse1,
    supplierId: supplierIds.supplier1,
    isActive: true,
  },
  {
    id: productIds.product3,
    name: 'Shantui SL36-B3 Wheel Loader',
    description: 'Wheel Loader for construction and material handling',
    category: PRODUCT_CATEGORY.SERIALIZED,
    machineTypeId: 'wheelLoader',
    unitOfMeasureId: 'pcs',
    brandId: 'shantui',
    model: 'SL36-B3',
    serialNumber: 'SHA-SL36B3-2019-003',
    machineNumber: 'WL-2019-003',
    year: 2019,
    condition: 'used',
    status: 'in_stock',
    price: '95000000.00',
    engineModel: 'WD10G220E23',
    enginePower: '220 hp',
    operatingWeight: '18,500 kg',
    warehouseId: warehouseIds.warehouse1,
    supplierId: supplierIds.supplier1,
    isActive: true,
  },
  {
    id: productIds.product4,
    name: 'Shantui DH08-B3-XL Bulldozer',
    description: 'Bulldozer for earthmoving and construction',
    category: PRODUCT_CATEGORY.SERIALIZED,
    machineTypeId: 'bulldozer',
    unitOfMeasureId: 'pcs',
    brandId: 'shantui',
    model: 'DH08-B3-XL',
    serialNumber: 'SHA-DH08B3XL-2024-004',
    machineNumber: 'BD-2024-004',
    year: 2024,
    condition: 'new',
    status: 'in_stock',
    price: '220000000.00',
    engineModel: 'Cummins NT855-C360',
    enginePower: '360 hp',
    operatingWeight: '32,000 kg',
    warehouseId: warehouseIds.warehouse1,
    supplierId: supplierIds.supplier1,
    isActive: true,
  },
  {
    id: productIds.product5,
    name: 'Shantui SFD35-3000 Excavator',
    description: 'Excavator for construction and digging operations',
    category: PRODUCT_CATEGORY.SERIALIZED,
    machineTypeId: 'excavator',
    unitOfMeasureId: 'pcs',
    brandId: 'shantui',
    model: 'SFD35-3000',
    serialNumber: 'SHA-SFD35-2022-005',
    machineNumber: 'EX-2022-005',
    year: 2022,
    condition: 'used',
    status: 'maintenance',
    price: '165000000.00',
    engineModel: 'Cummins NT855-C360',
    enginePower: '360 hp',
    operatingWeight: '35,000 kg',
    warehouseId: warehouseIds.warehouse1,
    supplierId: supplierIds.supplier1,
    isActive: true,
  },
  {
    id: productIds.product6,
    name: 'Caterpillar D6T Bulldozer',
    description: 'Heavy-duty bulldozer for large-scale earthmoving projects',
    category: PRODUCT_CATEGORY.SERIALIZED,
    machineTypeId: 'bulldozer',
    unitOfMeasureId: 'pcs',
    brandId: 'caterpillar',
    model: 'D6T',
    serialNumber: 'CAT-D6T-2024-006',
    machineNumber: 'BD-2024-006',
    year: 2024,
    condition: 'new',
    status: 'in_stock',
    price: '450000000.00',
    engineModel: 'Caterpillar C11 ACERT',
    enginePower: '330 hp',
    operatingWeight: '22,000 kg',
    warehouseId: warehouseIds.warehouse2,
    supplierId: supplierIds.supplier2,
    isActive: true,
  },
  {
    id: productIds.product7,
    name: 'Komatsu PC200-8 Excavator',
    description: 'Medium-sized excavator for versatile construction work',
    category: PRODUCT_CATEGORY.SERIALIZED,
    machineTypeId: 'excavator',
    unitOfMeasureId: 'pcs',
    brandId: 'komatsu',
    model: 'PC200-8',
    serialNumber: 'KOM-PC200-2021-007',
    machineNumber: 'EX-2021-007',
    year: 2021,
    condition: 'used',
    status: 'reserved',
    price: '280000000.00',
    engineModel: 'Komatsu SAA6D107E-1',
    enginePower: '103 kW',
    operatingWeight: '20,000 kg',
    warehouseId: warehouseIds.warehouse1,
    supplierId: supplierIds.supplier3,
    isActive: true,
  },
];
