import { products as productsSchema } from '../schema';
import { productIds, supplierIds, warehouseIds } from './seed-constants';

export type NewProduct = typeof productsSchema.$inferInsert;

export const products: NewProduct[] = [
  {
    id: productIds.product1,
    code: 'SHA-L36B3-2025-001',
    name: 'Shantui L36-B3 Wheel Loader',
    description: 'Wheel Loader for construction and material handling',
    category: 'serialized',
    machineTypeId: 'wheelLoader',
    unitOfMeasureId: 'pcs',
    brandId: 'shantui',
    model: 'L36-B3',
    serialNumber: 'SHA-1750609617450-853',
    machineNumber: 'WL-2025-001',
    year: 2025,
    condition: 'new',
    status: 'in_stock',
    price: '185000000.00',
    engineModel: 'WD10G220E23',
    enginePower: '220 hp',
    operatingWeight: '18,500 kg',
    warehouseId: warehouseIds.warehouse1,
    supplierId: supplierIds.supplier1,
    isActive: true,
  },
  {
    id: productIds.product2,
    code: 'SHA-L36B3-2023-002',
    name: 'Shantui L36-B3 Wheel Loader',
    description: 'Wheel Loader for construction and material handling',
    category: 'serialized',
    machineTypeId: 'wheelLoader',
    unitOfMeasureId: 'pcs',
    brandId: 'shantui',
    model: 'L36-B3',
    serialNumber: 'SHA-1749810376237-569',
    machineNumber: 'WL-2023-002',
    year: 2023,
    condition: 'used',
    status: 'reserved',
    price: '145000000.00',
    engineModel: 'WD10G220E23',
    enginePower: '220 hp',
    operatingWeight: '18,500 kg',
    warehouseId: warehouseIds.warehouse1,
    supplierId: supplierIds.supplier1,
    isActive: true,
  },
  {
    id: productIds.product3,
    code: 'SHA-SL36B3-2019-003',
    name: 'Shantui SL36-B3 Wheel Loader',
    description: 'Wheel Loader for construction and material handling',
    category: 'serialized',
    machineTypeId: 'wheelLoader',
    unitOfMeasureId: 'pcs',
    brandId: 'shantui',
    model: 'SL36-B3',
    serialNumber: 'SHA-1749809344351-476',
    machineNumber: 'WL-2019-003',
    year: 2019,
    condition: 'used',
    status: 'in_stock',
    price: '95000000.00',
    engineModel: 'WD10G220E23',
    enginePower: '220 hp',
    operatingWeight: '18,500 kg',
    warehouseId: warehouseIds.warehouse1,
    supplierId: supplierIds.supplier1,
    isActive: true,
  },
  {
    id: productIds.product4,
    code: 'SHA-DH08B3XL-2024-004',
    name: 'Shantui DH08-B3-XL Bulldozer',
    description: 'Bulldozer for earthmoving and construction',
    category: 'serialized',
    machineTypeId: 'bulldozer',
    unitOfMeasureId: 'pcs',
    brandId: 'shantui',
    model: 'DH08-B3-XL',
    serialNumber: 'SHA-1749715519206-385',
    machineNumber: 'BD-2024-004',
    year: 2024,
    condition: 'new',
    status: 'in_stock',
    price: '220000000.00',
    engineModel: 'Cummins NT855-C360',
    enginePower: '360 hp',
    operatingWeight: '32,000 kg',
    warehouseId: warehouseIds.warehouse1,
    supplierId: supplierIds.supplier1,
    isActive: true,
  },
  {
    id: productIds.product5,
    code: 'SHA-SFD35-2022-005',
    name: 'Shantui SFD35-3000 Excavator',
    description: 'Excavator for construction and digging operations',
    category: 'serialized',
    machineTypeId: 'excavator',
    unitOfMeasureId: 'pcs',
    brandId: 'shantui',
    model: 'SFD35-3000',
    serialNumber: 'SHA-1749713879644-288',
    machineNumber: 'EX-2022-005',
    year: 2022,
    condition: 'used',
    status: 'maintenance',
    price: '165000000.00',
    engineModel: 'Cummins NT855-C360',
    enginePower: '360 hp',
    operatingWeight: '35,000 kg',
    warehouseId: warehouseIds.warehouse1,
    supplierId: supplierIds.supplier1,
    isActive: true,
  },
];
