import { userIds } from './seed-constants';

// Use a fixed password hash for all users
const hashedPassword =
  '$2b$12$Sr7vKhJv/7gfaeOrEghHFuYpHRe8ZgQ/3rMM9XFTNcw8bAkvY6paO'; // password123

export const users = [
  {
    id: userIds.admin_ho_jakarta,
    code: 'ADMIN01',
    firstName: 'Admin',
    lastName: 'IT support',
    NIK: '1234567890123456',
    email: 'admin@sti.com',
    password: hashedPassword,
    jobTitle: 'IT Support',
    joinDate: new Date('1998-06-12'),
    type: 'full-time',
    phone: '+6281234567890',
    avatar: null,
    role: 'staff',
    branchId: 'ho_jakarta', // Admin at HO Jakarta
    signature: null,
    isActive: true,
    isAdmin: true,
  },
  {
    id: userIds.staff_pekanbaru,
    code: 'USR001',
    firstName: 'Asep',
    lastName: 'Staff',
    NIK: '1234567890123461',
    email: 'staff@sti.com',
    password: hashedPassword,
    jobTitle: 'Sales Staff',
    joinDate: new Date('2024-01-15'),
    type: 'full-time',
    phone: '+6281234567890',
    avatar: null,
    role: 'staff',
    branchId: 'pekanbaru', // Sales staff at Pekanbaru
    signature: null,
    isActive: true,
    isAdmin: false,
  },
  {
    id: userIds.manager_kendari,
    code: 'USR002',
    firstName: 'Budi',
    lastName: 'Manager',
    NIK: '1234567890123457',
    email: 'manager@sti.com',
    password: hashedPassword,
    jobTitle: 'Sales Manager',
    joinDate: new Date('2023-06-01'),
    type: 'full-time',
    phone: '+6281234567891',
    avatar: null,
    role: 'manager',
    branchId: 'kendari', // Sales manager at Kendari
    signature: null,
    isActive: true,
    isAdmin: false,
  },
  {
    id: userIds.user3,
    code: 'USR003',
    firstName: 'Rizky',
    lastName: 'Director',
    NIK: '1234567890123458',
    email: 'director@sti.com',
    password: hashedPassword,
    jobTitle: 'Director',
    joinDate: new Date('2022-01-01'),
    type: 'full-time',
    phone: '+6281234567892',
    avatar: null,
    role: 'director',
    branchId: 'ho_jakarta', // Director at HO Jakarta
    signature: null,
    isActive: true,
    isAdmin: false,
  },
  {
    id: userIds.user4,
    code: 'USR004',
    firstName: 'Rini',
    lastName: 'Susanti Staff',
    NIK: '1234567890123459',
    email: 'staff2@sti.com',
    password: hashedPassword,
    jobTitle: 'Sales Staff',
    joinDate: new Date('2024-03-01'),
    type: 'full-time',
    phone: '+6281234567893',
    avatar: null,
    role: 'staff',
    branchId: 'balikpapan', // Sales staff at Balikpapan
    signature: null,
    isActive: true,
    isAdmin: false,
  },
  {
    id: userIds.user5,
    code: 'USR005',
    firstName: 'Dani',
    lastName: 'Import Manager',
    NIK: '1234567890123460',
    email: 'import@sti.com',
    password: hashedPassword,
    jobTitle: 'Import Manager',
    joinDate: new Date('2023-09-15'),
    type: 'full-time',
    phone: '+6281234567894',
    avatar: null,
    role: 'import-manager',
    branchId: 'ho_jakarta', // Import manager at HO Jakarta
    signature: null,
    isActive: true,
    isAdmin: false,
  },
];
