import { warehouseIds } from './seed-constants';

export const warehouses = [
  {
    id: warehouseIds.warehouse1,
    code: 'WH001',
    name: 'Warehouse Jakarta Pusat',
    address: 'Jl. Warehouse No. 1',
    city: 'Jakarta',
    country: 'Indonesia',
    manager: 'Warehouse Manager Jakarta',
    phone: '+6281234567895',
    isActive: true,
  },
  {
    id: warehouseIds.warehouse2,
    code: 'WH002',
    name: 'Warehouse Surabaya',
    address: 'Jl. Warehouse No. 2',
    city: 'Surabaya',
    country: 'Indonesia',
    manager: 'Warehouse Manager Surabaya',
    phone: '+6281234567896',
    isActive: true,
  },
  {
    id: warehouseIds.warehouse3,
    code: 'WH003',
    name: 'Warehouse Bandung',
    address: 'Jl. Warehouse No. 3, Bandung',
    city: 'Bandung',
    country: 'Indonesia',
    manager: 'Warehouse Manager Bandung',
    phone: '+6281234567897',
    isActive: true,
  },
  {
    id: warehouseIds.warehouse4,
    code: 'WH004',
    name: 'Warehouse Medan',
    address: 'Jl. Warehouse No. 4, Medan',
    city: 'Medan',
    country: 'Indonesia',
    manager: 'Warehouse Manager Medan',
    phone: '+6281234567898',
    isActive: true,
  },
];
